FROM jupyter/minimal-notebook:latest

RUN conda install -c conda-forge mamba -y && \
    mamba install -c conda-forge dask distributed -y && \
    conda clean --all -f -y

WORKDIR /home/jovyan/work

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]