apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-jupyter
  labels:
    app: dask-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-jupyter
  template:
    metadata:
      labels:
        app: dask-jupyter
    spec:
      containers:
      - name: dask-jupyter
        image: kind-registry:5000/dask-jupyter:latest
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: dask-jupyter-volume
          mountPath: /home/jovyan/work
        imagePullPolicy: Always
      volumes:
      - name: dask-jupyter-volume
        emptyDir: {}