apiVersion: apps/v1
kind: Deployment
metadata:
  name: kind-registry
  labels:
    app: kind-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kind-registry
  template:
    metadata:
      labels:
        app: kind-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
      volumes:
      - name: registry-storage
        emptyDir: {}
