apiVersion: v1
kind: Service
metadata:
  name: kind-registry
  labels:
    app: kind-registry
spec:
  selector:
    app: kind-registry
  ports:
  - name: registry
    protocol: TCP
    port: 5000
    targetPort: 5000
