apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    app: dask-scheduler
spec:
  selector:
    app: dask-scheduler
  ports:
  - name: dask-scheduler
    protocol: TCP
    port: 8786
    targetPort: 8786
  - name: dask-dashboard
    protocol: TCP
    port: 8787
    targetPort: 8787