apiVersion: v1
kind: Service
metadata:
  name: dask-jupyter
  labels:
    app: dask-jupyter
spec:
  type: NodePort
  selector:
    app: dask-jupyter
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30036